language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

os:
  - linux
  - osx

before_script:
  - composer self-update
  - composer install -o --prefer-source

script:
  - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

